AllCops:
  DisplayCopNames: true

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 100
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - main.rb
  Max: 50


